### ISSUE TITLE
cannot restart container

### ISSUE THREAD

**Issue by qlex** [pelias/dockerfiles#11]
When trying to restart container, i typed in "docker-compose down" as instructed in wiki and got errors below. Of course, I cannot successully start "docker-compose up" and even if i killed -9 node with pelias process and build.sh doesnt work anymore.

Stopping pelias_api ... error
Stopping` pelias_pip ... error
Stopping pelias_placeholder ... error
Stopping pelias_interpolation ... error
Stopping pelias_elasticsearch ... error

ERROR: for pelias_elasticsearch  Cannot stop container 734892b101eed17790955b12c9d5576e8d42ccf4a3aaa145eb6e7ac3fad3f912: Cannot kill container 734892b101eed17790955b12c9d5576e8d42ccf4a3aaa145eb6e7ac3fad3f912: rpc error: code = 14 desc = grpc: the connection is unavailable

ERROR: for pelias_pip  Cannot stop container 82644549ecf8026fc16cc02b56dc9377a4506e42a2e49e520bf0725ba894f645: Cannot kill container 82644549ecf8026fc16cc02b56dc9377a4506e42a2e49e520bf0725ba894f645: rpc error: code = 14 desc = grpc: the connection is unavailable

ERROR: for pelias_interpolation  Cannot stop container 48f17d45306fcc2f1531da4261db6c0c297dc8db60a10d16febe25404d831a4f: Cannot kill container 48f17d45306fcc2f1531da4261db6c0c297dc8db60a10d16febe25404d831a4f: rpc error: code = 14 desc = grpc: the connection is unavailable

ERROR: for pelias_placeholder  Cannot stop container cab862063e92632b604cec222dd312130824efde3d5d1b53f87039ad59054220: Cannot kill container cab862063e92632b604cec222dd312130824efde3d5d1b53f87039ad59054220: rpc error: code = 14 desc = grpc: the connection is unavailable

ERROR: for pelias_api  Cannot stop container abf8d30cb4e26077bc18a3fc51e5dc79ee00cf3d5de7837592ca56799370851d: Cannot kill container abf8d30cb4e26077bc18a3fc51e5dc79ee00cf3d5de7837592ca56799370851d: rpc error: code = 14 desc = grpc: the connection is unavailable

**Comment by missinglink** [comment]
hi @qlex I have not seen this error myself, could you please provide some more information about your system, ie: operating system, RAM, any special setup.

from a quick google it seems like the `grpc: the connection is unavailable` error is also affecting other people and may be a docker bug...

**Comment by dianashk** [comment]
Thanks for reporting the issue. We haven't seen this on our testing but we'll try to investigate what's going on. If you have any additional insight into your setup we'd appreciate that. Which version of docker and docker-compose are you running? Which OS are you on? 
Cheers!

**Comment by wkulesza** [comment]
Im using VM machine running Debian 8.8 with 4gb ram - all on my laptop. After that, we want to install the docker on dedicated server with Debian 8.6 and 16+gb of ram and also similar machine with ubuntu 14.04.1. This should be enough as we're only using it for one metropolitan area in Poland.

**Comment by orangejulius** [comment]
Closing this old issue, hopefully the http://github.com/pelias/docker/ repository which replaces this one has fixed this issue. If not, feel free to open an issue there with the latest info on the issue. Thanks!
