### ISSUE TITLE
Request for San Francisco Bay Area config file

### ISSUE THREAD

**Issue by 3vivekb** [pelias/dockerfiles#16]
Alongside the portland example, can a San Francisco Bay Area example config file be created as well?

**Comment by orangejulius** [comment]
This is a cool idea. I'm not sure how many would be practical but there's no reason we couldn't have pre-built examples for a few popular cities.

**Comment by missinglink** [comment]
Hey @3vivekb, I'm not American and not totally 100% on what's defined as the Bay Area, assuming SF and Oakland?

If you could definitely which areas you need I can look in to creating the config file for you.

**Comment by 3vivekb** [comment]
San Francisco Bay Area usually includes everything in [ABAG](http://www.bayareacensus.ca.gov/counties/counties.htm).

**Comment by dustyny** [comment]
I would also suggest having config files that demonstrate how to add countries & continents.

**Comment by orangejulius** [comment]
Closing this because we've migrated from https://github.com/pelias-deprecated/dockerfiles to http://github.com/pelias/docker/, which is better set up to support many config files. As a popular area, a SF Bay area project configuration would be a great addition from someone looking to contribute.
