### ISSUE TITLE
libpostal error on build

### ISSUE THREAD

**Issue by darkyelox** [pelias/dockerfiles#29]
I try to use the docker version of pelias, i clone the repository and then do ./build and for 1 hour of work at final i get this log with errors:

```
FAIL: test_libpostal
============================================================================
Testsuite summary for libpostal 1.0.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
============================================================================
make[3]: *** [test-suite.log] Error 1
Makefile:794: recipe for target 'test-suite.log' failed
make[3]: Leaving directory '/code/libpostal/test'
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
Makefile:900: recipe for target 'check-TESTS' failed
make[2]: Leaving directory '/code/libpostal/test'
Makefile:973: recipe for target 'check-am' failed
make[1]: Leaving directory '/code/libpostal/test'
make: *** [check-recursive] Error 1
Makefile:454: recipe for target 'check-recursive' failed
ERROR: Service 'libpostal_baseimage' failed to build: The command '/bin/sh -c ./bootstrap.sh &&     ./configure --datadir=/usr/share/libpostal &&     make && make check && make install &&     ldconfig' returned a non-zero code: 2

real	63m32.221s
user	0m10.204s
sys	0m1.200s
```

The process ends and when i do `docker-compose ps` there are only running:

```
pelias_baseimage       /bin/bash                        Exit 0                                                      
pelias_elasticsearch   /docker-entrypoint.sh elas ...   Up           0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp 
pelias_pip             npm start -- /data/whosonfirst   Restarting                                                  
pelias_placeholder     npm start                        Up           0.0.0.0:4100->4100/tcp 

```

So maybe i need to do a manual installation instead?

**Comment by orangejulius** [comment]
Hey @darkyelox,
Thanks for reporting this issue. Building all the Docker images from scratch, as you noticed, takes a long time. I also think it needs lots of RAM, if your machine doesn't have a lot (say, less than 8GB), that might be the problem.

Fortunately, we don't want everyone to have to always build the images. We are now building them frequently and pushing them to Docker Hub. Can you please try out [this pull request](https://github.com/pelias/dockerfiles/pull/26) which turns off local builds, and should instead default to pulling the latest images from Docker Hub? It should work better and be quite a bit faster.

**Comment by darkyelox** [comment]
@orangejulius Hi, thanks in fact was the low memory (2 GB only) i will try with more memory (8GB) and disk space (80GB) but trying your commit i get this:

```
ERROR: build path /root/pelias-docker/libpostal_baseimage either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /root/pelias-docker/libpostal_baseimage either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /root/pelias-docker/libpostal_baseimage either does not exist, is not accessible, or is not a valid URL.
waiting for elasticsearch service to come up
...............................................................................................................................................
```

and the process never start, i will try with the original dockerfiles.

**Comment by orangejulius** [comment]
Hey @darkyelox,
Oh yes, thanks for catching that. I had removed one of the Dockerfiles when I shouldn't have. Please pull that branch again (it was force pushed), and try once more. It now pulls all new images for me. Of course feel free to build if you'd like :)

**Comment by orangejulius** [comment]
I think we fixed this, and I also believe this particular issue is no longer possible since we've switched to a libpostal service in #42. Feel free to comment or re-open if there is more though.
