### ISSUE TITLE
Interpolation not working as of November 7, 2017

### ISSUE THREAD

**Issue by fpurcell** [pelias/dockerfiles#38]
I am again seeing interpolation not work properly (November 7, 2017).   I had seen similar issues previously, ala #25 .  This is on a system cleaned of older docker containers and data, and running the dockerfiles' build.sh with minimal changes (only change is adding the key to pelias.json).

This call should show an interpolated address:
https://ws-st.trimet.org/pelias/v1/search?text=888%20SE%20Lambert%20St  

But instead, I get this: ![interpolation](https://user-images.githubusercontent.com/64323/32583311-d2042da6-c4a7-11e7-809b-89af89607241.png)

I'm guessing these build.sh errors are part of the problem:
ESC[32minfoESC[39m: [update_tiger] Downloaded tl_2016_41071_addrfeat.zip
Starting pelias_baseimage
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.9.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 65, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 117, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 712, in run
    run_one_off_container(container_options, self.project, service, options)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 998, in run_one_off_container
    pty.start(sockets)
  File "/usr/lib/python2.7/site-packages/dockerpty/pty.py", line 334, in start
    self._hijack_tty(pumps)
  File "/usr/lib/python2.7/site-packages/dockerpty/pty.py", line 373, in _hijack_tty
    pump.flush()
  File "/usr/lib/python2.7/site-packages/dockerpty/io.py", line 378, in flush
    raise e
OSError: [Errno 9] Bad file descriptor
Starting pelias_baseimage

Here's the full log from running dockerfiles/build.sh:  
[build.log](https://github.com/pelias/dockerfiles/files/1455973/build.log)

**Comment by missinglink** [comment]
hi, @fpurcell I haven't seen that issue before (I'm on linux), is this error on linux/osx?

there are a few issues mentioning `OSError: [Errno 9] Bad file descriptor` in other projects such as:
https://github.com/docker/compose/issues/3491

**Comment by missinglink** [comment]
could you please try the `-T` flag for `docker-compose run` as mentioned in that issue:

```
$ docker-compose run --help
Run a one-off command on a service.

For example:

    $ docker-compose run web python manage.py shell

By default, linked services will be started, unless they are already
running. If you do not want to start linked services, use
`docker-compose run --no-deps SERVICE COMMAND [ARGS...]`.

Usage: run [options] [-p PORT...] [-e KEY=VAL...] SERVICE [COMMAND] [ARGS...]

Options:
    -d                    Detached mode: Run container in the background, print
                          new container name.
    --name NAME           Assign a name to the container
    --entrypoint CMD      Override the entrypoint of the image.
    -e KEY=VAL            Set an environment variable (can be used multiple times)
    -u, --user=""         Run as specified username or uid
    --no-deps             Don't start linked services.
    --rm                  Remove container after run. Ignored in detached mode.
    -p, --publish=[]      Publish a container's port(s) to the host
    --service-ports       Run command with the service's ports enabled and mapped
                          to the host.
    -T                    Disable pseudo-tty allocation. By default `docker-compose run`
                          allocates a TTY.
    -w, --workdir=""      Working directory inside the container
```

**Comment by missinglink** [comment]
looking through the commits, it looks like we have only made minor dependency updates in the last few months, I can't pinpoint any change which would have caused this change in behaviour.

https://github.com/pelias/interpolation/commits/master

**Comment by fpurcell** [comment]
Hey Peter,

Success!  Thanks for the help...

>  I haven't seen that issue before (I'm on linux), is this error on linux/osx?

we're using Linux 3.10.0 / CentOS 7 (3.10.0-693.2.2.el7.x86_64) on a virtual machine.


> could you please try the -T flag for docker-compose run

in prep_data.sh, I did a bulk replace of "docker-compose run " to add the -T option to all run commands, and I think that's a really good add.  I'm no longer seeing any "OSError: [Errno 9] Bad file descriptor" errors.  It could be my imagination, but the build also seems a bit snappier.  I seem to remember more pauses between various commands (at least when watching the logged output)

Here's the file: [prep_data.sh](https://github.com/pelias/dockerfiles/files/1458529/prep_data.txt)

Thanks,
Frank

**Comment by missinglink** [comment]
Great news @fpurcell, would you like to open a PR to upstream these changes or would you prefer if I do it and you could test it for me?

**Comment by missinglink** [comment]
I'm still very curious why this used to work and then stopped working, is it possible that some other dependency version was changed, such as the docker version?

**Comment by fpurcell** [comment]
Hey Peter,  I'll let you make the -T changes ... I'm not in the best position to test anything more than CentOS.  Plus, you may choose to be more selective in the use of the -T option.

About why it worked, then stopped, I can't say. What I can say is that this same pattern repeated a  couple of times in the past. Without the -T, the docker stuff and tty seemed pretty finicky, where things would work consistently well for a period of time (end of August...first weeks of October); then there were updates to some dependant Pelias containers and I would see issues consistently  with "OSError: [Errno 9] Bad file descriptor" screwing up loading (early September, early November).
