### ISSUE TITLE
Looking for paid installation service

### ISSUE THREAD

**Issue by SumeetMoray** [pelias/dockerfiles#40]
Sorry this is not the right place to post this. 

Feel free to delete this Issue after keeping it for few days !

I need a self-hosted pelias Geocoder for our taxi booking app. 
But i am finding it quite difficult to install it by myself !

Can anyone help me install pelias geocoder on Digital Ocean VPS ? 
You can ask for payments and charges ! 

If you guys help me install pelias how much will you charge for your service ?

**Comment by orangejulius** [comment]
Hi @SumeetMoray,
Thanks for reaching out. We're happy to help with specific installation issues here. Post some details on what you're trying to do and the errors or problems you are seeing, and we'll be glad to take a look.

Beyond that, you can send an email to pelias.team@gmail.com if you're looking for some paid support, we might be able to work something out. I'll close this issue but feel free to open a new one around specific issues in the code.
