### ISSUE TITLE
mem_limit setting in docker-compose.yml was causing imports to fail

### ISSUE THREAD

**Issue by chriswhong** [pelias/dockerfiles#41]
I am leaving an issue here for posterity and google-ability in case anyone encounters this.

Our custom importer was always failing around 3.75M rows, with errors about lost socket connections... it would retry a bunch, and eventually resume, but pelias-dbclient's logging would say we lost several batches.

After trying everything under the sun, it was this `mem_limit` that seemed to be affecting things.  Once we removed it and rebuilt the container, we didn't see the issue again.

**Comment by orangejulius** [comment]
This was probably done to keep the memory usage in check. We did most of our development with Portland and Boston, both much smaller cities. We'll look at bumping this up.

**Comment by orangejulius** [comment]
We've actually fixed the need to raise this limit up much, if at all, with changes to the Pelias schema such as https://github.com/pelias/schema/pull/302. Let us know in the new http://github.com/pelias/docker/ if anyone is still having trouble with this.
