### ISSUE TITLE
whosonfirst does not start with default pelias.json configuration

### ISSUE THREAD

**Issue by PhilGBr** [pelias/dockerfiles#44]
Hi everybody.
I'm trying to install and run a pelias instance for testing and learning purpose. I'm on macOS Sierra.

I (think I) correctly followed the guidelines provided in the read.me. But I'm facing an issue related to whosonfirst postal codes import.

**Configuration**
I used the same as default (except I put my mapzen-key-id !!).

![image](https://user-images.githubusercontent.com/12731940/36321187-402bcfb0-1349-11e8-97d5-41b09ec63e05.png)

It means that:
- only data from the Portland area will be imported
- postal codes will be imported
 
**The problem I have**
The download phase (`docker-compose run --rm whosonfirst npm run download`) works fine. In particular, 26 postal codes were imported

Below is an extract of the log:
![image](https://user-images.githubusercontent.com/12731940/36321736-25017eb8-134b-11e8-84ec-a5cab73bc0d7.png)

Later on, during the import phase (`docker-compose run --rm whosonfirst npm start`), I got an error when the program tries to import the postal codes data. 

Here are the logs:
![image](https://user-images.githubusercontent.com/12731940/36322503-baca540e-134d-11e8-9569-bb5a7459c760.png)

My understanding is that, even if the scope is reduced to Portland (`"importPlace": "101715829"` is set in the pelias.json properties file), the program doesn't take this configuration into account and assume that all postal codes need to be indexed, and thus all postal codes files should be available.

Am I correct ? Or do I miss something ?

After some googling, I found  [whosonfirst issue #230](https://github.com/pelias/whosonfirst/issues/230). It seems to confirm my assumptions. 

So, if is correct, it would be worth:
- changing the default pelias.json file and set `"importPostalcodes": false`
- adding an explanation in the read.me related to postal codes

What do you think ?

Best,
Philippe

**Comment by orangejulius** [comment]
Hey Philippe,
Thanks for the report. Is it possible that postalcode meta files were downloaded by some other means? For example, perhaps you did a full WOF download separately? Check what's in the directory pointed to by the `DATA_DIR` variable in the `.env` file in your checkout of the dockerfiles repo.

I just tried this out myself, and it worked for me right now, but there are quite a few moving pieces, so it's very possible there are bugs if people don't follow the exact steps we do. Any such bugs we would very much like to fix, so I'd love to track this down.

**Comment by PhilGBr** [comment]
Hi Julian,

I only used the pelias-dockerfile resources (no "manual" download or anything else).But I'm beginning with Pelias, and I did a few mistakes (like forgetting to set the "api_key" in pelias.json, ...) and ran into issues.
So I had to rerun several times some part of the import. Maybe I changed something in the config at one moment, and I forgot it.

I'm gonna do it again from scratch and I'll keep you posted about the outcome...

Thank you

**Comment by PhilGBr** [comment]
Hi Julian,

So I started over from scratch, and it went well this time. 

Doing that, I noticed that I previously had two different values set  for the DATA_DIR variable:

- in my `.env` file, `DATA_DIR` was set to `/tmp/pelias`
- in the shell session used to launch the `build.sh` script,  `DATA_DIR `was set to `/tmp`

Maybe this explains the issue I ran into.

Thank you for your help.

Philippe

**Comment by orangejulius** [comment]
Ah, this makes a lot of sense. We've already heard about the pain of managing `DATA_DIR` in two places in https://github.com/pelias/dockerfiles/issues/8. We definitely need to figure something out that's more foolproof. Thanks for the feedback, and if you have any ideas, let us know.

**Comment by orangejulius** [comment]
Hey @PhilGBr,
I think we've fixed this with https://github.com/pelias/dockerfiles/pull/53, as it's no longer necessary to set `DATA_DIR` in two places. If you've had a chance to test things out since then let me know.

**Comment by orangejulius** [comment]
Closing this old issue, hopefully the http://github.com/pelias/docker/ repository which replaces this one has fixed this issue. If not, feel free to open an issue there with the latest info on the issue. Thanks!
