### ISSUE TITLE
Wall of errors during successful setup, not sure what is wrong

### ISSUE THREAD

**Issue by mapmeld** [pelias/dockerfiles#46]
Toward the end of Docker setup of Pelias, I got trapped in what looked like an infinite loop printing many errors over and over.. I hit Ctrl+C to stop this part of the process.  Everything else installed cleanly and the geocoder is working on some addresses. Any idea what glitched here?

```
Elasticsearch ERROR: 2018-02-27T21:34:03Z
  Error: Request error, retrying
  POST http://elasticsearch:9200/_bulk => socket hang up
      at Log.error (/code/pelias/openaddresses/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/code/pelias/openaddresses/node_modules/elasticsearch/src/lib/transport.js:258:18)
      at HttpConnector.<anonymous> (/code/pelias/openaddresses/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
      at ClientRequest.bound (/code/pelias/openaddresses/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
      at emitOne (events.js:77:13)
      at ClientRequest.emit (events.js:169:7)
      at Socket.socketCloseListener (_http_client.js:245:9)
      at emitOne (events.js:82:20)
      at Socket.emit (events.js:169:7)
      at TCP._onclose (net.js:490:12)

Elasticsearch WARNING: 2018-02-27T21:34:03Z
  Unable to revive connection: http://elasticsearch:9200/

No living connections

error: [dbclient] esclient error Error: No Living connections
    at sendReqWithConnection (/code/pelias/openaddresses/node_modules/elasticsearch/src/lib/transport.js:225:15)
    at next (/code/pelias/openaddresses/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
error: [dbclient] invalid resp from es bulk index operation

info: [dbclient] retrying batch [429]
error: [dbclient] [429] type=es_rejected_execution_exception, reason=rejected execution of org.elasticsearch.transport.TransportService$4@167c6af0 on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@43c5e68[Running, pool size = 4, active threads = 4, queued tasks = 50, completed tasks = 110]]
```

**Comment by orangejulius** [comment]
Hey @mapmeld!
We've been getting lots of reports of this lately.

What part of the world did you try to import? We know the current configuration works for Portland, OR, but it's a pretty small city, so bigger areas may currently cause problems. Over in #41 changing the [memory limit](https://github.com/pelias/dockerfiles/blob/master/docker-compose.yml#L146) for the Elasticsearch container seemed to help. 

Can you do two things for me?

1. run `curl localhost:9200/_cat/indices` with Elasticsearch from the container running, and paste the output. That will show how much is stored in Elasticsearch so far
2. try again after bumping the memory limit, maybe to 2g or 4g?

If it works after that, then that's pretty great. We'll bump the memory limit to a reasonable number for small installations. If not, I've been meaning to test out some fixes for https://github.com/pelias/dbclient/issues/76, which might be related.

**Comment by mapmeld** [comment]
I was trying to do the recommended setup with Portland and greater CPU/memory preferences for Docker, which is why this was confusing.

```
localhost:9200/_cat/indices
> green open pelias 1 0 72500 2929 25.1mb 25.1mb
```

**Comment by orangejulius** [comment]
Okay, definitely not the memory limit then. I also re-ran the default Portland import and am seeing the same thing. So something broke recently.

It's almost certainly related to https://github.com/pelias/dbclient/issues/76. According to that issue, we suspect our importers might essentially be sending a huge number of Elasticsearch bulk index requests in parallel, which isn't very nice for Elasticsearch. We should be able to limit it to say, 2 or 3 requests in flight at a time, and it will all work fine.

**Comment by orangejulius** [comment]
@mapmeld another thing to try is the changes in #59. In my experience our choice to run the importers in parallel is a little risky when running locally (it definitely makes sense when doing a full planet build with lots of machines on EC2 though).

**Comment by orangejulius** [comment]
Closing this old issue, hopefully the http://github.com/pelias/docker/ repository which replaces this one has fixed this issue. If not, feel free to open an issue there with the latest info on the issue. Thanks!
