### ISSUE TITLE
How to configure pelias.json if multiple regions/cities need to be imported?

### ISSUE THREAD

**Issue by jengeb** [pelias/dockerfiles#49]
Assuming that I need to import the datasets for Idaho and Oregon, I would adjust the imports in pelias.json. I would configure the id of `importPlace`, e.g. Idaho for the whosonfirst dataset as follows and run the build script.

```
    "whosonfirst": {
      "datapath": "/data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true,
      "importPlace": "85688657",
      "api_key": "your-api-key"
    }
```

After this I would like to import the dataset for Oregon with the `importPlace` id 85688513. What's the best way to do that? Changing the pelias.json file and running the build script again for each region?

**Comment by orangejulius** [comment]
For now, yes running the WOF importer twice would be the best way. @missinglink and I were just discussing allowing importPlace to contain an array of IDs so that several areas could be imported.

**Comment by jengeb** [comment]
@orangejulius Thanks for your help and quick response.
