### ISSUE TITLE
error when executing "docker-compose run --rm whosonfirst npm run download" error:14077410:SSL routines:SSL23_GET_SERVER_HELLO

### ISSUE THREAD

**Issue by jradcgo** [pelias/dockerfiles#50]
Hello colleagues, he tried to follow the instructions of the document how_to_guide.pdf but I was stuck in this error that I could not solve:

![1](https://user-images.githubusercontent.com/25774436/37218990-bbaef5c4-2387-11e8-96e7-2541244725c2.png)

PS C:\Users\andres.castillo\dockerfiles> docker-compose run --rm whosonfirst npm run download
Starting pelias_baseimage ... done

> pelias-whosonfirst@0.0.0-semantic-release download /code/pelias/whosonfirst
> node ./utils/download_data.js

2018-03-09T16:53:06.032Z - info: [download_data_filtered] Getting parent ids
2018-03-09T16:53:06.304Z - error: [download_data_filtered] { Error: write EPROTO 140406295983936:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:812:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
2018-03-09T16:53:06.307Z - error: [download_data_filtered] "failed to get place info"

# **## I did the same procedure on linux and the same error appeared :(**

This is my pelias.json:

{
  "esclient": {
    "hosts": [{ "host": "elasticsearch" }]
  },
  "api": {
    "textAnalyzer": "libpostal",
    "services": {
      "placeholder": {
      "url": "http://placeholder:4100"
      }
    }
  },
  "imports": {
    "whosonfirst": {
      "datapath": "/data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true,
      "importPlace": "85950361",  //costa rica
      "api_key": "xxxx" // my apikey
    }
  }
}

**Comment by orangejulius** [comment]
Hi @jradcgo,
Thanks for reporting this. I'm sure many other people are experiencing this so it's good to have such a detailed issue.

This is happening because Mapzen shut down, and took with it the Who's on first API we were using to download data for just one particular region, rather than the entire planet. We are building a replacement for this API that runs locally over in https://github.com/pelias/whosonfirst/pull/324 and it will be done soon.

If you want to try it out now, that would be a big help. You can make a change like this to`docker-compose.yml`:
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 2e6a9f5..8834966 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -45,7 +45,7 @@ services:
       - "${DATA_DIR}:/data"
   whosonfirst:
     depends_on: [ "baseimage" ]
-    image: pelias/whosonfirst
+    image: pelias/whosonfirst:region_extract_from_sqlite
     container_name: pelias_whosonfirst
     networks: [ "pelias" ]
     volumes:
```

Alternatively I made that change in a branch: https://github.com/pelias/dockerfiles/tree/tmp_whosonfirst_branch

**Comment by jradcgo** [comment]
Hi @orangejulius 

Excellent, thank you very much for the info. I'm going to try it

**Comment by jradcgo** [comment]
Hi @orangejulius

Thank you very much for helping us
It seems that your solution works, but now this error appears:

![2](https://user-images.githubusercontent.com/25774436/37229511-c60d906c-23a9-11e8-9331-449b9130b616.png)

I have the latest version of node.js and npm installed, 

I have to accept that I'm not familiar with this technology, for which I would appreciate the help

**Comment by orangejulius** [comment]
Hey @jradcgo,
How much disk space do you have available? One downside to the new approach is it requires downloading about 17GB worth of data, and you temporarily need 30GB to extract it. Here's the contents of my data directory, so you can verify everything looks the same.

```
julian@manhattan ~/repos/pelias/dockerfiles/pelias_data/whosonfirst $ ls sqlite/ -lh
total 17G
-rw-r--r-- 1 root root  15G Feb 28 20:00 whosonfirst-data-latest.db
-rw-r--r-- 1 root root 1.4G Feb 28 19:01 whosonfirst-data-postalcode-us-latest.db
julian@manhattan ~/repos/pelias/dockerfiles/pelias_data/whosonfirst $ md5sum sqlite/*.db
a3ed4438443fc6cfe88ab963c9161c78  sqlite/whosonfirst-data-latest.db
d72879cefd398fcc71c343d2c73895dc  sqlite/whosonfirst-data-postalcode-us-latest.db
```

**Comment by jradcgo** [comment]
Hello @orangejulius 

I think I have no problem with that,(I have more than 200 GB of space on C:/)


In fact, I ran the command again and now if I am downloading the .dbz2 file 

Note: Before executing the command, I had already manually downloaded the .dbz2, can I just move it to / pelias / dockerfiles / pelias_data / whosonfirst / sqlite and continue with the guide? (so as not to wait for the download again)

*Solo en mi idioma natal le puedo agradecer enormemente por la gran ayuda que me ha brindado*
Pura vida

**Comment by orangejulius** [comment]
Yes, you definitely can copy it there. It could be a path issue then if you're running it on windows, but give it another shot, maybe it will just work? :)

**Comment by jradcgo** [comment]
Dear @orangejulius 

Is this result the expected one?


![3](https://user-images.githubusercontent.com/25774436/37233134-93ab62c6-23b7-11e8-8d41-5c69b4f7aca8.png)

![image](https://user-images.githubusercontent.com/25774436/37233174-c42f2874-23b7-11e8-9750-cc55d9ed0ad6.png)

![image](https://user-images.githubusercontent.com/25774436/37233182-ce458506-23b7-11e8-8137-7e9adffb9983.png)

![image](https://user-images.githubusercontent.com/25774436/37233199-e44e1318-23b7-11e8-8a68-731f615f9a0e.png)

I have doubts with those files practically empty :/
¡Gracias de antemano!

**Comment by jradcgo** [comment]
I think my doubt has materialized :(

![image](https://user-images.githubusercontent.com/25774436/37233414-af2b6040-23b8-11e8-91e8-f3cadd8dff54.png)

**Comment by orangejulius** [comment]
You're right, empty files are not expected. Can you try on a Linux machine? We do not officially support windows, and it's unlikely we would be able to spend the time to make it work there soon :(

Edit: then again, the dockerfiles should remove most windows-specific bugs. But please try just to see if it makes a difference :)

**Comment by jradcgo** [comment]
What a pity , but the experience will help me to do it on Linux next week
1000 thanks Mr. Julian

**Comment by orangejulius** [comment]
Closing this old issue, hopefully the http://github.com/pelias/docker/ repository which replaces this one has fixed this issue. If not, feel free to open an issue there with the latest info on the issue. Thanks!
