### ISSUE TITLE
The link to sign up and generate a Mapzen API key doesn't work 

### ISSUE THREAD

**Issue by jengeb** [pelias/dockerfiles#55]
The [how-to guide](https://github.com/pelias/dockerfiles/blob/master/how_to_guide.pdf) states that you need an API key to configure the whosonfirst import. The sign-up [link](https://mapzen.com/developers/sign_up) doesn't work right now. I am aware that Mapzen is shutting down its services. :-( So how will this be handled as from now on? 

I ask because it seems necessary to use an API key in `pelias.json`:

```json
    "whosonfirst": {
      "datapath": "/data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true,
      "importPlace": "101715829",
      "api_key": "your-api-key"
    },
```

**Comment by orangejulius** [comment]
Hey @jengeb,
We no longer require the `api_key` parameter. We've built functionality into Pelias to replace what was previously handled by a Mapzen API. If you try the dockerfiles setup again (simply running`./build.sh` should be enough, as it will download updated images), it should now work.

Let me know how it goes!
