### ISSUE TITLE
env var DATA_DIR not set

### ISSUE THREAD

**Issue by qlex** [pelias/dockerfiles#8]
Maybe a dumb question, but eventough i created /tmp/data folder, upon ./build.sh I'm getting:
env var DATA_DIR not set error.

**Comment by dianashk** [comment]
Hi @qlex! Excellent question. There are many ways to set that DATA_DIR environment variable. If you're running the build.sh script it needs to be explicitly exported or specified along with the execution.

```
export DATA_DIR=/tmp/data 
./build.sh
```

Or 

```
DATA_DIR=/tmp/data ./build.sh
```

**Comment by kannes** [comment]
https://github.com/pelias/dockerfiles#prerequisites says to 

> A directory for storing downloaded datasets. Set DATA_DIR to the folder's path in .env file.

which did nothing for me. Maybe qlex was misled by that just like I was.

**Comment by orangejulius** [comment]
Hey @qlex and @kannes,

Thanks for pointing this out. It looks like the code is a bit torn between two approaches: using a shell environment variable, as @dianashk suggested above, and using the `.env` file which is used only by `docker-compose`.

One option we could take to fix this would be to remove [the line that checks for that environment variable](https://github.com/pelias/dockerfiles/blob/master/build.sh#L2) in `build.sh`. However, then it would be required that we build checking for that environment variable into each of our Docker images (I think), which would be rather repetitive.

The other option is to use only shell environment variables, and drop usage of the `.env` file completely. Then all our scripts can directly enforce needed variables. The downside here is `docker-compose up` by itself would probably not work.

**Comment by orangejulius** [comment]
Hi all. We've discovered in #48 that we can make our shell scripts _and_ docker-compose use the `.env` file fairly easily. So now there's no need to run `export DATA_DIR=...` any more, and only one place to keep up to date!
